### ISSUE TITLE
psl.isValid inconsistency with Amazon S3 urls

### ISSUE THREAD

**Issue by Slapbox** [lupomontero/psl#258]
```js

psl.isValid('s3.amazonaws.com') // false ??? Why???
psl.isValid('s3.amazonaws.co.uk') // true
psl.isValid('s2.amazonaws.com') // true
psl.isValid('s4.amazonaws.com') // true
psl.isValid('s33.amazonaws.com') // true
```

**Comment by Slapbox** [comment]
Can anyone explain what the rule for `s3.amazonaws.com` is for? I'm not grasping the rationale.

https://github.com/lupomontero/psl/blob/master/data/rules.json#L7381

In our use case we have a url like `https://s3.amazonaws.com/somebucket.com/index.html` and we strip everything but the hostname, `s3.amazonaws.com` to check if it's valid. Using `psl.isValid(someURL)` works for this use case for every other type of URL, but it can't recognize `s3.amazonaws.com` as valid due to that rule.

**Comment by z639** [comment]
I think that is the correct result.

If you read this https://github.com/lupomontero/psl/issues/23 lupomontero explains more.

What I do to check if the domain is valid, meaning has a valid TLD (and this might not be completely correct, but is working for me so far) is to just check if it is listed.

In your example that would be...

psl.parse.(someURL).listed // true if valid TLD and false otherwise.

**Comment by Slapbox** [comment]
Thanks for sharing that @z639! I think that will work for us too.

I tried for a while to find a related issue but since I was only searching for `s3.amazonaws` that didn't come up.

Thanks again!
