### ISSUE TITLE
AWS endpoints in data differ from AWS documentation

### ISSUE THREAD

**Issue by SebieF** [lupomontero/psl#293]
Hello,

some endpoint addresses of AWS services in [rules.json](https://github.com/lupomontero/psl/blob/e8877e40e88e4472827dfa6e421fff2f3467f967/data/rules.json#L7397) differ from the official addresses in the [AWS documentation](
https://docs.aws.amazon.com/general/latest/gr/s3.html). For example:
```bash
# Rules.json
"s3-us-west-1.amazonaws.com"
# AWS Docs
"s3.us-west-1.amazonaws.com"
```

This is probably a minor issue, but still wanted to let you know.

**Comment by lupomontero** [comment]
Hi @SebieF, thanks for reporting this and many apologies for the delay in getting back to you...

The `rules.json` file contains the actual Public Suffix List as published and maintened at https://publicsuffix.org/ . In order to change an entry in this file it would probably make sense to have the change applied directly to the list itself. Once updated upstream we can easily pull the updated list.

More info on [how to submit changes to the Public Suffix List here](https://publicsuffix.org/submit/)

I hope this helps :smile:

**Comment by lupomontero** [comment]
Closing this issue as this no longer applies. The list was eventually updated upstream.
