### ISSUE TITLE
punycode is deprecated in Node v21

### ISSUE THREAD

**Issue by AnWeber** [lupomontero/psl#315]
Using punycode is deprecated in Node v21. See documentation https://nodejs.org/api/punycode.html. Maybe try replacing with NPM Package [punycode](https://www.npmjs.com/package/punycode)

punycode is used here: https://github.com/lupomontero/psl/blob/797ccb41136a75b5737ea1e4d2bdcaad0dac02de/index.js#L5

Fix:
1. `npm i punycode` 
2. change from `require("punycode")` to `require("punycode/")`

https://github.com/AnWeber/httpyac/issues/577

**Comment by AnWeber** [comment]
There is already a pull request from 2022 fixing this issue. 

#298

**Comment by quinton-ashley** [comment]
@lupomontero

**Comment by ed-25519** [comment]
https://github.com/lupomontero/psl/commit/3ddec00372501a4657d28fbd87e6fd59db12a897
See this commit and I may suggest that new version be released soon.

**Comment by jm42** [comment]
This is already fixed. We are just waiting for a new release. Patience is a virtue.

**Comment by MikeMcC399** [comment]
@jm42 

> This is already fixed. We are just waiting for a new release. Patience is a virtue.

Can you clarify why you suggest just waiting? Are you a maintainer and you are planning a release?

It's 2 months ago since @lupomontero added a series of commits into the `master` branch including the fix https://github.com/lupomontero/psl/commit/3ddec00372501a4657d28fbd87e6fd59db12a897 for this issue.

If you are not a maintainer, then perhaps @lupomontero could say if/when a new release is planned?

**Comment by skagedal** [comment]
Thank you for maintaining this package! I understand that it is a lot of work. It would be appreciated with a release that includes thix fix.

**Comment by NullVoxPopuli** [comment]
when is the next release? it's been almost a year.

thanks!

**Comment by lupomontero** [comment]
Hi there, many apologies for taking so long to address this... I have just released a new version that should include a fix for this issue: https://github.com/lupomontero/psl/releases/tag/v1.10.0
