### ISSUE TITLE
error

### ISSUE THREAD

**Issue by elvinzhu** [lupomontero/psl#326]
![image](https://github.com/user-attachments/assets/f755c0ce-8ab5-4ab1-bf5c-ddb9f0c80856)

tks

**Comment by AlexWebLab** [comment]
Same here. Pipeline broken.
I've added
`"peerDependencies": {
    "psl": "1.10.0"
  }`
on my package.json file

**Comment by SJ-Workforce** [comment]
They started using
` import Punycode from 'punycode/punycode.js';`

instead of 

`var Punycode = require('punycode/');`

in new psl v1.11.0

**Comment by SJ-Workforce** [comment]
Updating used node helped when dependency was installed in pipeline.
But devs of psl clearly should have used v2 instead of 1.11 when updating.

**Comment by lupomontero** [comment]
Looking into this right now... :cold_sweat: Will report back very soon

**Comment by lupomontero** [comment]
@elvinzhu, what version of Node.js is that on?

**Comment by elvinzhu** [comment]
> @elvinzhu, what version of Node.js is that on?

14.16

**Comment by attitudeuser** [comment]
> of

we also meet this question，vNode.js 10.21.0

**Comment by RudiVuuren** [comment]
> "devDependencies": { "psl":"1.10.0", }

I highly encourge you to look into using [override](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) instead

**Comment by luboslav** [comment]
NPM override is available from version 8.3.0, we are using older node/npm versions.

**Comment by lupomontero** [comment]
Can you guys provide a bit more context about your stack and your use case? Are you depending directly on `psl` or is it buried down in the dependency tree?

Looking at @elvinzhu's screenshot it looks like you are running a script (`node scripts/install.js`).  Can you please provide some info about what happens in that script and how `psl` is being used/installed?

I can also see a previous prompt showing something related to `node-sass`. Is that related to the issue?

As @SJ-Workforce commented, this should probably have been a major release and not a minor... I underestimated the implications. [ECMAScript modules are considered _stable_ since Node.js 12](https://nodejs.org/docs/latest-v12.x/api/esm.html#introduction), so I assumed... and probably shouldn't have :see_no_evil: 

Just in case, in older Node.js versions you can also try importing the UMD provided (`require('psl/dist/psl.umd.cjs')`).

**Comment by SJ-Workforce** [comment]
package 'node-sass: ^4.13.1' is using package 'request: ^2.88.0',
and it uses package 'tough-cookie: ~2.5.0', which uses package 'psl: ^1.1.28'

this ^1.1.28 is used as 1.11.0

**Comment by Lamarcke** [comment]
> Can you guys provide a bit more context about your stack and your use case? Are you depending directly on `psl` or is it buried down in the dependency tree?
> 
> Looking at @elvinzhu's screenshot it looks like you are running a script (`node scripts/install.js`). Can you please provide some info about what happens in that script and how `psl` is being used/installed?
> 
> I can also see a previous prompt showing something related to `node-sass`. Is that related to the issue?
> 
> As @SJ-Workforce commented, this should probably have been a major release and not a minor... I underestimated the implications. [ECMAScript modules are considered _stable_ since Node.js 12](https://nodejs.org/docs/latest-v12.x/api/esm.html#introduction), so I assumed... and probably shouldn't have 🙈
> 
> Just in case, in older Node.js versions you can also try importing the UMD provided (`require('psl/dist/psl.umd.cjs')`).

I think that some versions (~4.x.x) of node-sass (which are being used by some older angular projects) are being automatically updated to the latest version of PSL, and so their install scripts are being botched by the latest changes. Thing is, these projects are probably still using Node 8 or Node 10.

I'm using a very old project of a angular builder library which uses `psl` under the hood (as a very deep sub dependency), and since that project is not actively maintained anymore, there is not much i can do.

I honestly think it's not your fault, since we are using versions of NodeJS that have long lost support. I do agree with @SJ-Workforce though, a major version would prevent this issue for most older libraries.

**Comment by bergamin** [comment]
@lupomontero

> Can you guys provide a bit more context about your stack and your use case? Are you depending directly on `psl` or is it buried down in the dependency tree?

![image](https://github.com/user-attachments/assets/9961b0e3-8773-4ef6-bde0-26068bca4ac6)

- Angular 8
- Node: 10.23.1

**Comment by attitudeuser** [comment]
It's also  appear at package 'less':3.0.4 --> 'request':2.88.2-->'tough-cookie':2.5.0

**Comment by aydinbulut** [comment]
We also have issue because of this update now. We are using node v10.24.1. PSL is a transitive(indirect, dependency of another dependency) dependency. NPM's overrides is not possible with node v10.24.1. PSL is dependency of multiple other dependencies. You could have released this change as version v2 since it is breaking?

**Comment by cmhernandezdel** [comment]
Same here using node 10.16. Uploaded my docker image and worked well, and 5 minutes later tried to upload the same image to another repo and it started to fail.

**Comment by aydinbulut** [comment]
> > We also have issue because of this update now. We are using node v10.24.1. PSL is a transitive(indirect, dependency of another dependency) dependency. NPM's overrides is not possible with node v10.24.1. PSL is dependency of multiple other dependencies. You could have released this change as version v2 since it is breaking? With renaming to v2 it would be pickup in our build process and wouldn't breake.
> 
> @aydinbulut We also use `node v10.24.1`, adding `"psl": "1.10.0"` into `dependencies` (not `devDependencies`) build again.

This seems working, I will be doing smoke testing.

**Comment by jlaule** [comment]
Same issue and we are using node 18.16.0. As was mentioned above, this change should have been done as v2.0.0 instead of 1.11.0. How soon can this be fixed. Not easy to update numerous packages to override this one item.

This shows as a dependent install for tough-cookie which is utilized under depndencies for jest and tedious packages.

+-- jest@26.6.3
| `-- @jest/core@26.6.3
|   `-- jest-config@26.6.3
|     `-- jest-environment-jsdom@26.6.2
|       `-- jsdom@16.7.0
|         `-- tough-cookie@4.1.4
|           `-- **psl@1.11.0 deduped**
`-- tedious@8.3.1
  `-- @azure/ms-rest-nodeauth@2.0.2
    +-- @azure/ms-rest-js@1.11.2
    | `-- tough-cookie@2.5.0
    |   `-- psl@1.11.0
    `-- adal-node@0.1.28
      `-- request@2.88.2
        `-- tough-cookie@2.5.0
          `-- **psl@1.11.0 deduped**

**Comment by OskarLebuda** [comment]
The problem is you defined `exports` in `package.json` and you removed the `main` section. The `exports` is not available for old node versions like 10. You have to define the `main` as well for backport compatibility. I've created a PR for that: https://github.com/lupomontero/psl/pull/327

**Comment by mfink-db** [comment]
for me jest is breaking due to commonJS import ( application is using commonJS on node v20)

``` 
APP_PATH/node_modules/psl/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import Punycode from 'punycode/punycode.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/request/node_modules/tough-cookie/lib/pubsuffix-psl.js:32:11)
      at Object.<anonymous> (node_modules/request/node_modules/tough-cookie/lib/cookie.js:35:17)
      at Object.<anonymous> (node_modules/request/lib/cookies.js:3:13)
      at Object.<anonymous> (node_modules/request/index.js:18:15)
      at Object.<anonymous> (node_modules/@sendgrid/client/src/classes/client.js:6:14)
      at Object.<anonymous> (node_modules/@sendgrid/client/src/client.js:6:16)
      at Object.<anonymous> (node_modules/@sendgrid/client/index.js:3:16)
      at Object.<anonymous> (node_modules/@sendgrid/mail/src/classes/mail-service.js:6:18)
      at Object.<anonymous> (node_modules/@sendgrid/mail/src/mail.js:6:21)
      ```

**Comment by dacoffey** [comment]
thanks for the quick fix 😀

> I have just released a new version (`v1.12.0`) reverting back to CommonJS. Hopefully this should solve this issue for the time being. The newer version with ESM support will soon be released as `v2.0`. Many apologies to all affected. This was my oversight. Best.

![image](https://github.com/user-attachments/assets/4537077e-051c-405d-b175-cec79de53a1f)

[XKCD](https://www.explainxkcd.com/wiki/index.php/2347:_Dependency)

**Comment by mikeedmond** [comment]
> I have just released a new version (`v1.12.0`) reverting back to CommonJS. Hopefully this should solve this issue for the time being. The newer version with ESM support will soon be released as `v2.0`. Many apologies to all affected. This was my oversight. Best.

Thanks for the quick response. We are also suffering this problem and unfortunately, I'm not sure the new 1.12.0 package helps. It's being included deep down in our dependency tree so we can't easily change the version pulled in. We're currently trying to use the override in packages.json but it's not ideal.

**Comment by lupomontero** [comment]
> Thanks for the quick response. We are also suffering this problem and unfortunately, I'm not sure the new 1.12.0 package helps. It's being included deep down in our dependency tree so we can't easily change the version pulled in.

@mikeedmond, I'm assuming the dependency responsible for including `psl` is declaring the `psl` dependency using a caret (ie: `^v1.2.3`), so new installs will automatically pickup minor releases. If this is the case, reinstalling should fix it. If it doesn't, can you please  try to remove installed deps (`rm -rf node_modules package-lock.json`) and `npm install` again?

**Comment by mikeedmond** [comment]
Yes, thanks. I realized shortly after posting my comment so quickly deleted it - seemingly not quickly enough. Sorry for having posted in haste, but thanks for the reply.

Thanks too for the quick turn around on the fix, really appreciate it!

Best regards,

Mike.


Mike Edmond
Software Team Leader
Bemrose House, Bemrose Park, Wayzgoose Drive, Derby, DE21 6XQ, United Kingdom
+44 (0)1332 294 441 | www.datapath.co.uk
Datapath Ltd.  Registered Number: 1609392.  Registered in England at Bemrose House, Bemrose Park, Wayzgoose Drive, Derby. DE21 6XQ.
________________________________
