### ISSUE TITLE
`github.io` domains results invalid

### ISSUE THREAD

**Issue by shivashanmugam** [lupomontero/psl#88]
![image](https://user-images.githubusercontent.com/6939456/63264917-e5ab9680-c2a9-11e9-99de-1e7fa2699294.png)

sub-domain with  `github.io` results invalid

https://runkit.com/shivashanmugam/5d5a918aeaec0b0014422629

**Comment by lupomontero** [comment]
Hi @shivashanmugam,

Thanks for raising this issue.

This is a common misconception with the Public Suffix List (PSL). From the point of view of the Public Suffix List, in the case of of `google.github.io`, the whole thing is the Public Suffix, as this represents the point at which _ownership_ is granted. By this I mean that the _owner_ of the content under `google.github.io` is not the same as `github.io`, they are both independent public suffixes. However, on the other hand, the owner of `google.github.com` is indeed the same as `github.com`. This is why the results are different, and this is the expected behaviour.

The confusion arises as this module assigns the public suffix to a property called `domain`, which I admit is confusing (it was inherited from an older library originally written for Ruby). In this case, `domain` really means the _public suffix_, which is used to determine _ownership_ or control, and not the same as DNS.

> A "public suffix" is one under which Internet users can (or historically could) directly register names.
> Source: https://publicsuffix.org/

I hope this helps.

**Comment by shivashanmugam** [comment]
thanks for the clarificatino @lupomontero
