### ISSUE TITLE
PSL test caese failing on power machine

### ISSUE THREAD

**Issue by dipika21** [lupomontero/psl#98]
npm version : 5.10.0
node version : 8.9.4
phantomjs version : 2.1.1 (binary created from source code)

successfully working on X86 ubuntu.

But facing below issue on Power RHEL while **npm test -f**:
>> 57 tests completed
>> 48 tests failed
![psl](https://user-images.githubusercontent.com/40032958/64405395-9a142d80-d09c-11e9-91b0-ac666f4a0c6e.PNG)

Any lead would be helpful.
Thanks.

**Comment by lupomontero** [comment]
Hi @dipika21, thanks for reporting this. At first glance I'm not sure what the problem is... :thinking: ... 

Can you please confirm which version of RHEL you are using? I'm assuming this is [RHEL on IBM Power](https://access.redhat.com/solutions/1124983)? It would be very helpful to know these details in order to set up an environment where to reproduce the issue :wink:

**Comment by dipika21** [comment]
RHEL 7.3

yes, it is IBM power, and facing issue for testcase failure (as shown in screenshot)

**Comment by lupomontero** [comment]
It's been 5 years since this was reported... :see_no_evil: ... and we are no longer using PhantomJS, so cloding this issue assuming it no longer applies.
